### ISSUE TITLE
Accessibility issues in a GUI

### ISSUE THREAD

**Issue by Kazaf123** [die-tageszeitung/tazapp-android#11]
**Description**
This is a feature request about components that have accessibility issues within the GUI of such an App.
Also, as the following Figure, this report focuses on the content GUI page in the App.
<img width="360" alt="MuMu20221128092546" src="https://user-images.githubusercontent.com/44084361/204172743-d2565dea-5f6c-4daf-872d-9e60d60528bf.png">
**Content**
After I applied my proposed tool to detect this GUI, I found that the input boxes are too close so that low-vision users easily touch them by mistake, could they be a little bit further apart?
Thanks a lot~!

**Comment by eikectrlaltcoop** [comment]
Hi,
thanks for your Feature request. But this app is not maintained anymore.
You can find the actual reader app of the taz at https://github.com/die-tageszeitung/taz-neo
