### ISSUE TITLE
Enable F-Droid Version of the TAZ app

### ISSUE THREAD

**Issue by kirschner** [die-tageszeitung/tazapp-android#3]
There are some proprietary libraries in the TAZ app, which prevent a build for the TAZ app for F-Droid. @grote removed the proprietary libraries here: https://github.com/grote/tazapp-android/tree/libre and I tested that version for several months now without any noticeable problems. It seems those libraries (mainly google firebase) are not needed to read the TAZ if you do not need push notifications. 

Would it be possible to add a Free Software / Libre flavour, which could then be used for a build for F-Droid? This way TAZ readers who do not want to share their data with Google by using an account for Google Play, could still benefit from updates for the TAZ app, instead of the current -- inconvenient and insecure -- practice to receive APKs from the TAZ team. 

(See also http://blogs.taz.de/hausblog/2016/04/25/taz-app-goes-open-source/ for some other comments about F-Droid.)

Thank you very much for considering this feature request.

**Comment by matecode** [comment]
Hi! It is possible to download the taz.app directly as apk from taz servers. I don't know the direct url, but I implemented a way to update the app without using google play then, if you installed not with googleplay. I suggest that you write to app@taz.de to get thje direct download url.

**Comment by kirschner** [comment]
@matecode Yes, I know about that possibility and friends used that in the past. But it is problematic for updates. 

As Tagesschau now also has an own F-Droid repository https://service.tagesschau.de/app/repo/ I thought this might also be an option for the TAZ, or to just use the libre fork and get it into the official F-Droid repository.

**Comment by woffs** [comment]
I have rebased grote/libre and removed some other stuff too: https://github.com/woffs/tazapp-android/tree/libre-rebased but this is rather dirty, although I could build it locally with fdroid
https://gitlab.com/woffs/fdroiddata/tree/tazapp and the resulting apk works fine for me.
I'm not an Android developer. I'll try to find out how to push that into a more beautiful and sustainable shape.

**Comment by woffs** [comment]
See also https://gitlab.com/fdroid/fdroiddata/merge_requests/4545

**Comment by woffs** [comment]
closed via https://gitlab.com/fdroid/fdroiddata/commit/cea80c401f64459736f2575ba1022d1d62d921bc

**Comment by newsgrep** [comment]
**Thank you for committing the app to F-Droid.**
Some hints:
* Please do not put the changelog into the Summary (shall not excised 80 char) of the app. Instead put it into the Description. Also a CHANGES file would be helpful. 

* Please mark the links in the description as links. e.g.:
'''Zur Nutzung ist ein Abonnement nötig''', was unter [https://taz.de/!p4350/] bestellt werden kann.  

* Please add Links about: IssueTracker, Changelog & the WebSite to the reference section of the app description. 

More Information: 
https://f-droid.org/docs/Build_Metadata_Reference/
https://f-droid.org/docs/FAQ_-_App_Developers/

**Comment by woffs** [comment]
I do not understand your comment regarding the changelog in the summary. The changelog is in the changelog, and the summary is in the short_description.txt.

Please note that the F-Droid fork resides on https://github.com/woffs/tazapp-android

**Comment by katebaba** [comment]
The f-droid fork of Taz app fails while attempting downloads with a network error.
Non f-droid versions are working fine (besides of Google push functionality)
Any solutions or suggestions?
Thanks

The Version: 3.9.2.3+fdroid+universal (3090203)

Installations-ID: 785e6b50-1321-4ab9-95b6-5079070dedb1
Android Version: 28 (9)
samsung SM-T580 / gtaxlwifi / gtaxlwifi / samsung
Architektur: arm64-v8a,armeabi-v7a,armeabi
RAM: 969 (1943)
Speicher: /storage/emulated/0/Android/data/de.thecode.android.tazreader/files (frei: 15,3GB)-droid Fork
